### ISSUE TITLE
collection issues

### ISSUE THREAD

**Issue by HeSe** [svenvc/NeoJSON#1]
Hi! 

I just ported the current version to Gemstone 3.1.0.5 but I have trouble with a collection including obejcts within the same class hierarchy.

How would the neoJSONMapping: look like for a collection containing testObject2s and estObject3s ?

I trid to work with encoder and decoder custom mappings. But I can't get it working.

Could somebody please add an according test?

Thanks
Sebastian

**Comment by svenvc** [comment]
In more recent versions of STON, classes are serialized as
```
Class[#Point]
```
https://github.com/svenvc/ston/blob/master/ston-spec.md
