### ISSUE TITLE
NeoJSONObject at:ifPresent:ifAbsentPut: is broken on Pharo 8

### ISSUE THREAD

**Issue by gcotelli** [svenvc/NeoJSON#10]
Try inspecting the following
```
| o|
o := NeoJSONObject new.
o at: #x ifPresent: [] ifAbsentPut: [ 6 ].
o
```
It works in Pharo 9.

**Comment by gcotelli** [comment]
I've tried to debug the problem and seems that somehow the `orderedKeys` instance variable is not updated to contain the newly inserted key.

**Comment by gcotelli** [comment]
```
| o|
o := NeoJSONObject new.
o at: #x ifPresent: [] ifAbsentPut: [ 6 ].
o keys includes: #x.  "false"
o includesKey: #x. "true"
o includesKey: #x printString  "'{ Error printing JSON: Error: JSON key names in objects must be strings'"
```

**Comment by svenvc** [comment]
Yesterday I did https://github.com/svenvc/NeoJSON/commit/109d08bb08216b1ae583861a5c631cc0a564d248

It must be a problem with OrderedDictionary in general in Pharo 8 then.

**Comment by svenvc** [comment]
I fails in Pharo 7 as well, and for OrderedDictionary on its own:
```
o := OrderedDictionary new.
o at: #x ifPresent: [] ifAbsentPut: [ 6 ].
o keys includes: #x.
o includesKey: #x.
o at: #x.
o printString.
```

**Comment by svenvc** [comment]
https://github.com/pharo-project/pharo/pull/5974

**Comment by svenvc** [comment]
the only solution that I see is a patch: overwrite the method on NeoJSONObject to fix the problem in Pharo 7 and 8 as follows:

```
at: key ifPresent: aPresentBlock ifAbsentPut: anAbsentBlock
	"Lookup the given key in the receiver. If it is present, answer the
	value of evaluating the first block optionally with the value associated
	with the key.
	Otherwise store and return the result of evaluating the second block as the
	new value of the key."

	^ self
		at: key
		ifPresent: aPresentBlock
		ifAbsent: [self at: key put: anAbsentBlock value]
```

**Comment by gcotelli** [comment]
I think the same because no new releases of Pharo7/8 will be produced. 

Do you want me to create a PR adding a package loaded conditionally for these Pharo versions patching the class?

**Comment by svenvc** [comment]
I know that this could be done conditionally per version, but I prefer to keep things as simple as possible.

I added an implementation note to the override: 

https://github.com/svenvc/NeoJSON/commit/d0b66e77dad0d88a7728e416cbe5ec47df552a8a

**Comment by gcotelli** [comment]
Thank you. I've re-run the workflows failing with this error and is now gone.
