### ISSUE TITLE
Mapping for basic classes?

### ISSUE THREAD

**Issue by dallinjdahl** [svenvc/NeoJSON#11]
I'm trying to provide a validated object from json, wherein I can guarantee that the types of the member variables are as expected.  My thought was to do this with value schemas, but it appears that there are no mappings defined for reading basic classes?  Specifically I'm trying to ensure that the member variables of an object are deserialized as an integer and bytestring respectively.  Should I be extending those classes to implement #neoJsonMapping?

**Comment by svenvc** [comment]
Hi,

This is something that I never considered. This feels more like validation than mapping.

Both JSON and Pharo/Smalltalk are fully dynamically typed. I know that it is possible to statically describe some JSON structures, but I would say that is an add-on and a personal choice.

If you would map to your own domain objects, you could add type checks to the setters.

Sven
