### ISSUE TITLE
Use platform specific newline characters

### ISSUE THREAD

**Issue by botwhytho** [svenvc/NeoJSON#12]
Use something like ` OSPlatform current lineEnding` instead of the current character, which I believe is the default for old versions of Mac OSes. This can probably be set at class initialization time to not need to calculate many times at runtime

**Comment by svenvc** [comment]
OK that makes sense. I will do that.

**Comment by botwhytho** [comment]
I started relevant discussion in Pharo discord about similar change in STON (https://discord.com/channels/223421264751099906/223421264751099906/937030470867238942), yanni user makes good point of generically exposing being able to define the type of newLine you want. Think that is sound, but also providing a default (seems like the platform default makes sense most of the time) would be a good default.

**Comment by botwhytho** [comment]
Thanks for quick response and fix!
