### ISSUE TITLE
Default class `fromString:` method to using `OrderedCollection` as it's `listClass`

### ISSUE THREAD

**Issue by botwhytho** [svenvc/NeoJSON#13]
Considering JSON is a mix of lists and mappings and you can add keys/values to Dictionaries, you should also be able to add elements to a list in an object that represents JSON. This simplifies some use-cases like data wrangling and interactive manipulation of JSON API responses, for example.

If you are open to contributions, can definitely open a PR, let me know.

I use NeoJSONObject a lot as the overriding of `doesNotUnderstand:` is GREAT for exploring deeply nested objects without getting very verbose in Pharo with many parenthesis and `at:` sends.

Do something like below instead of current code.

```Smalltalk
	^ (NeoJSONReader on: string readStream)
		  mapClass: NeoJSONObject;
		  listClass: OrderedCollection;
		  propertyNamesAsSymbols: true;
		  next
```

While this change is being considered, an even more flexible suggestion would be to subclass OrderedCollection (similarly to how NeoJSONObject subclasses Dictionary) and add a `doesNotUnderstand:` that does something similar to what it does in NeoJSONObject. For example:

- `atN` unary method to get value at index N, for example `at42` would return value at index 42. This enables introspecting into deeply nested objects more succinctly  (i.e. `myNeoJSONObject firstKey secondKey at42 thirdKey at7 fourthKey fifthKey`
- Similarly `atN:` would set a value at index N. This is more for consistency as you can already use `at:put:` but it could also make code slightly shorter.

**Comment by svenvc** [comment]
Hmm, I never felt a need to add to lists but I can imagine how this could be something that you want.

About the accessors for SequenceableCollections, you do know that #first, #second up to #ninth do already exist ? I am not sure that higher numbers make a lot of sense (i.e. that many people would need these).

I will think a bit about this one, but I am inclined to stay with array in the general case and the option to change the list class already exists.

**Comment by botwhytho** [comment]
Yeah, aware of those message sends. If you think these are not general enough use-cases/functionality then I can keep using extensions on my end (https://github.com/botwhytho/quick-edit/commit/e3b583f06adc600be1a21e2c01ebbdb169f10cfa). Just opened ticket in case more people could take advantage of functionality in a more central place like NeoJSON. Maybe changing default doesn't make sense but adding functionality does. Let me know and thanks for response.

**Comment by botwhytho** [comment]
I realize that I made two suggestions on this ticket making it not the most actionable. Think the `atN` suggestion with `doesNotUnderstand:` may not generalize much and has not much to do with the other change. Any thoughts on the main ask of this ticket: changing the default (or providing an easy way, even if not the default) `listClass` to `OrderedCollection`?

**Comment by svenvc** [comment]
Hi,

I am sorry, but I don't want to change the current default.

There is an easy way to configure a reader to be different, that feels like enough to me.

All you have to do is add your own entry points for parsing and printing, where a custom reader or writer is configured and used, and you are good to go.

I absolutely understand that you might prefer another approach, but I think the tools are there to give you the options you need.

Sven
