### ISSUE TITLE
Mapping to multiple classes/Using custom containers

### ISSUE THREAD

**Issue by sdasda7777** [svenvc/NeoJSON#17]
Hi, I'm writing a library for work with JSON-LD and I currently use generic mapping to Arrays and Dictionaries. However, due to how JSON-LD is defined, I do not know in any moment what the type of the object at hand is, and therefore I'm doing a lot of branching based on the type, which leads to long method bodies and just isn't very nice overall.

My question is, is it possible to tell NeoJSON to map the objects to multiple classes that I would create, so that I could use polymorphism instead? Or do you have recomendations on what I should do instead?

**Comment by svenvc** [comment]
The mapping available in NeoJSON is useful for certain cases but not all. JSON was deliberately designed to be simple. You need layers on top to do more complex things. Especially dynamic typing, either with class or type tags or nested structures, are way beyond the design goals of the mapping mechanism.

I had a quick look at JSON-LD and its complexity is beyond NeoJSON's mapping capabilities, IMHO.

In such cases, I always suggest to work in multiple steps: first use NeoJSON to go from JSON to Arrays and Dictionaries, then do other passes to convert and augment what you have.

**Comment by sdasda7777** [comment]
I see, thanks. What I was actually thinking was if I could basically inject my own classes for dictionary, array, etc. into NeoJSON, because that would help a lot, I think. However I get that this is a really niche application so it probably isn't worth the time to implement it, and I currently discovered a lot simpler way to do what I wanted anyways 😅

**Comment by svenvc** [comment]
OK.

But you can inject your own classes instead of Array and Dictionary!

Just call listClass: and mapClass: to configure your reader.

See https://github.com/svenvc/NeoJSON/issues/13

**Comment by sdasda7777** [comment]
Oh, I see, that's great to know, thanks! 😅
