### ISSUE TITLE
Sending #at:at: to NeoJSONObject with missing keys results in 'errorKeyNotFound' entry

### ISSUE THREAD

**Issue by jvalteren** [svenvc/NeoJSON#18]
**Bug description**
When sending #at:at: to a NeoJSONObject instance where key1 or key2 is missing, it does not signal an error but instead adds key 'errorKeyNotFound' with the missing key as value.

**To reproduce**
Open a playground and inspect the following:
```Smalltalk
NeoJSONObject new at: #key1 at: #key2
```

**Expected behavior**
Since sending a missing key with #at: returns nil, #at:at: should work the same.

**Comment by svenvc** [comment]
I committed the following: https://github.com/svenvc/NeoJSON/commit/3dc868944d6eb2ba65927d3018ad13d93a7c4905

**Comment by jvalteren** [comment]
Nice, thank you!
