### ISSUE TITLE
Invalid utf 16 surrogates accepted

### ISSUE THREAD

**Issue by ghplink** [svenvc/NeoJSON#20]
String containing characters \udbff\ue000 leads to invalid unicode codepoint  U+110000, which is outside the max allowed codepoint U+10FFFF. Method parseCharacterHex in NeoJSONReader should throw an error in such case.

Possible code:
```
codePoint > 16r10FFFF
	ifTrue: [self error: 'trailing surrogate ', trailSurrogate asBigEndianByteArray asHexString
		, ' leads to invalid unicode codepoint ', codePoint asBigEndianByteArray asHexString]
```

**Comment by svenvc** [comment]
Right, you are correct: that edge case should be guarded against.

Thanks for the feedback.

This commit should fix it, with a regression test case.

https://github.com/svenvc/NeoJSON/commit/b05162a6e420b501a87c6fc9503745b69d51237a

References

- https://datatracker.ietf.org/doc/html/rfc7159#section-7
- https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF
