### ISSUE TITLE
`nextAs:` taking a basic class

### ISSUE THREAD

**Issue by shingarov** [svenvc/NeoJSON#21]
This should probably be a continuation of the discussion in #11 , but GitHub doesn't seem to allow me to reopen it, so I am creating this one.

We have bumped into something similar to what @dallinjdahl is describing.  We are sending some complex objects from OCaml over the wire to Smalltalk.  Because ML is Hindley–Milner-typed, and these types are first-class data in OCaml, it's easy to automatically recreate the schema on the Smalltalk side.  Obviously, we know the types for every node in that schema, so there will be leaves known to be Strings and leaves known to be Integers.  The problem is that `#nextAs:` does not allow its argument to be basic (i.e. you cannot do something like `reader nextAs: String`).  For now I am getting around this by modifying the implementation of `#nextAs:` to check whether `schema` is "primitive" and if so, use `#next` instead.  Here: https://github.com/svenvc/NeoJSON/compare/master...shingarov:NeoJSON:ott

For me it works reasonably well, but I am not exactly happy to have my projects rely on a NeoJSON fork instead of contributing upstream.  OTOH I am not convinced this is "the correct thing to do" so I am not creating a PR from the `ott` branch, but I feel that at least an Issue discussion might be useful.

**Comment by shingarov** [comment]
FYI @janvrany

**Comment by shingarov** [comment]
(as an aside, if anyone is curious what "Ott" means and what are those "complex objects we are wiring over from OCaml", it's Peter Sewell's semantics-definition tool, kind of what BNF does for syntax, Ott does for operational semantics).

**Comment by svenvc** [comment]
I don't think I fully understand. Maybe you could give some example ?

You have some data structure in OCaml that you convert to JSON. Since you have type info, you have a schema. And then you generate the NeoJSON mapping on the OCaml side ?

How does that look ? The JSON itself and the schema ?

Maybe you can filter out the primitives on the OCaml side ?

Also, your test for isJsonPrimitive is a dynamic, while I would say that the list of primitive JSON types is fixed and could be hardcoded, no ?

**Comment by shingarov** [comment]
> And then you generate the NeoJSON mapping on the OCaml side?

It's a very simplistic at this point, really "the stupidest thing that will work".  Because the types don't change at runtime, I just dump Smalltalk source from OCaml (by an ad-hoc contraption) and then compile it in Smalltalk.  Each *record* datatype (e.g. `type some_type = { x : x_type;...}`, similar to a C struct) becomes a Smalltalk class, and on the class side there is a generated method
```
instVarTyping
  {
  #x  -> x_type.
  #y  -> String.
  }
```
(here x_type is another class); and then at deserialization time this is used by
```
Object class >> neoJsonMapping: mapper
  (self respondsTo: #instVarTyping) ifFalse: [ ^self ].
  mapper for: self do: [ :mapping |
    mapping mapAllInstVars.
    self instVarTyping do: [ :ass |
      | ivar itsClass |
      ivar := ass key. itsClass := ass value.
      itsClass
        classAndMethodFor: #neoJsonOn:
        do: [ :cls :cm | (cls = Object) | (cls = Collection) ifTrue: [ (mapping mapInstVar: ivar) valueSchema: itsClass ] ] 
        ifAbsent: #error
    ]
  ]
```

Then there are *variant* types (disjoint unions).  These are slightly more code but still straightforward.

And then there are *algebraic* types, (things like, say, `string * int`), we don't have these in normal Smalltalk-80.  (Slightly digressing, in the images I load NeoJSON into, there is the reification of categorial product, so you *can* multiply classes and the resulting product responds to `#neoJsonMapping: `, deserializing to a tuple (simply Array in Smalltalk)).

> your test for isJsonPrimitive is a dynamic, while I would say that the list of primitive JSON types is fixed and could be hardcoded, no?

Definitely possible — I did try hardcoding `#isJsonPrimitive` to answer `true` on `Boolean`, `String` etc and `false` on `Object`, and it works, but feels less satisfactory, because I think there is code duplication.  What isJsonPrimitive is saying is basically, "I know how to do JSON myself, by having my own `#neoJsonOn:`; don't bother with Object's `#neoJsonOn:`".  Which is tantamount to having a non-default `#neoJsonOn:`.  Hardcoding `#isJsonPrimitive` would thus be duplicating information already encoded somewhere else (namely, in the presence/absence of `#neoJsonOn:`).

> Maybe you can filter out the primitives on the OCaml side ?

Definitely possible — so in the above example the `#y->String` would be omitted from `#instVarTyping`.  It feels less satisfactory because there are several places where `#nextAs:` is sent (records, disjoint unions, ADTs) so it would mean either duplicate code, or refactoring the check to basically a facade in front of `#nextAs:` (huh... the latter doesn't seem like such a bad idea...)

**Comment by svenvc** [comment]
Hi,

Thanks for the explanation. It is an impressive and somewhat unexpected usage of the mapping code. It is good that you figured it out and made it work. At first glance, I would say that you got your use case working.

At this point I don't feel as if I would like to change anything in the base code itself. 

As you know, JSON is explicitly not typed and fully dynamic. There are many approaching that are being used to add forms of typing, schemas and mappings. I consider the current mapping system as imperfect, it works more or less, but it is not powerful enough for some.

Sven

**Comment by shingarov** [comment]
Thanks Sven!  I think at this point there isn't much to be added to this Issue, which we can view as a helpful and informative discussion of the matter.  Let's happily leave things where they are for now.

**Comment by svenvc** [comment]
Thanks for the feedback.
