### ISSUE TITLE
NeoJSONWriter method escapeUnicode: is missing

### ISSUE THREAD

**Issue by jsladitschek** [svenvc/NeoJSON#3]
method escapeUnicode: is missing in class NeoJSONWriter

**Comment by svenvc** [comment]
Hi,

Weird, but it seems that last time I did not sync/commit/push everything correctly. Now it has.

https://github.com/svenvc/NeoJSON/blob/master/repository/Neo-JSON-Core.package/NeoJSONWriter.class/instance/escapeUnicode..st

Sven
