### ISSUE TITLE
Base smalltalk system not documented

### ISSUE THREAD

**Issue by ghplink** [svenvc/NeoJSON#4]
Code seems to be for Pharo and is not useable in other smalltalk systems without adaptions, e.g. String>>streamContents: is not available in VisualWorks.

This should be mentioned in the documentation.

**Comment by svenvc** [comment]
Yes, it was written in/for Pharo. It should be reasonably portable to some other Smalltalk dialects. There is no claim that it is available for any Smalltalk, the diversity being too great. Sorry about that.
