### ISSUE TITLE
Preserving order of fields during serialization

### ISSUE THREAD

**Issue by GlennCavarle** [svenvc/NeoJSON#5]
Hi,
`NeoJSONWriter` do not preserve the order of fields which is defined in `#neoJsonMapping:` declarations.

example : 

```
neoJsonMapping: mapper
	mapper for: self do: [ :mapping | 
		(mapping mapInstVar: #id) valueSchema: UUID.
		(mapping mapInstVar: #text).
	]
```

will produce: 

```
{
	"text" : "Do something",
	"id" : "ee0a2a9c-ff32-0d00-ab55-ba1605c02387"
}
```

Maybe, using an `OrderedDictionary` for properties in `NeoJSONObjectMapping` could do the trick.

Cheers

**Comment by svenvc** [comment]
Glenn,

I was looking into this, but the IV properties in NeoJSONObjectMapping is already an OrderedCollection and thus keeps the order. Are you looking at an older version ?

Consider

````
String streamContents: [ :out |
	(NeoJSONWriter on: out) 
		for: Point do: [ :mapping |
			mapping mapInstVar: #x; mapInstVar: #y ];
		nextPut: { 1@2. 3@4 } ].

 '[{"x":1,"y":2},{"x":3,"y":4}]'.

String streamContents: [ :out |
	(NeoJSONWriter on: out) 
		for: Point do: [ :mapping |
			mapping mapInstVar: #y; mapInstVar: #x ];
		nextPut: { 1@2. 3@4 } ].
	
 '[{"y":2,"x":1},{"y":4,"x":3}]'
````

Does this work for you ?

Sven

**Comment by GlennCavarle** [comment]
Hi Sven,

My bad, you are right, this issue is already fixed on master.
My project uses the master branch of NeoJSON but it also uses Zinc which load the stable version of NeoJSON from http://mc.stfx.eu/Neo/ (Neo-JSON-Core-SvenVanCaekenberghe.33).
In this version 33 the issue is still there, the  IV properties is a Dictionary...

Thanks for your expertise, i close the issue.
Cheers,

Glenn.
