### ISSUE TITLE
Loading into Pharo causes IceAuthenticationError

### ISSUE THREAD

**Issue by riverdusty** [svenvc/NeoJSON#8]
Pharo Version 7 both x86 and x64 on Windows.
run the code 
```
Metacello new
  repository: 'github://svenvc/NeoJSON/repository';
  baseline: 'NeoJSON';
  load.
```
get:
![image](https://user-images.githubusercontent.com/572263/95567846-c4fd4d80-0a23-11eb-9c71-fadffe530b11.png)

To be clear, I can't get my end users to get github accounts or ssh keys just to load software. I'm also not going to put my ssh keys or github credentials into an image intended for distribution to the public.

I don't know why this is the only github repository that gives this issue.

**Comment by svenvc** [comment]
Your problem has nothing to do with NeoCSV IMHO (unless it works for other Pharo projects).

Of course you should be able to load projects from github anomymously.

This feels like a general problem with your installation of Pharo (7 on Windows).

I think it is best if you ask this question on the general mailing lists or discord channels.

**Comment by riverdusty** [comment]
> Your problem has nothing to do with NeoCSV IMHO (unless it works for other Pharo projects).
> 
> Of course you should be able to load projects from github anonymously.
> 
> This feels like a general problem with your installation of Pharo (7 on Windows).
> 
> I think it is best if you ask this question on the general mailing lists or discord channels.

The reason I posted it here is that I load XMLSuport and Roassal from github and they work.

```
	Metacello new
		baseline: 'XMLParser';
		repository: 'github://pharo-contributions/XML-XMLParser/src';
		load.
```
This works.
```
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3/src';
    load.
```
This works.

Since this is Pharo7 I have to do
```
	Metacello new
		repository: 'github://svenvc/zinc/repository';
		baseline: 'ZincHTTPComponents';
		load.
```
Which also works...

But:
```
	Metacello new
		repository: 'github://svenvc/NeoJSON/repository';
		baseline: 'NeoJSON';
		load.
```
Does not...

**Comment by svenvc** [comment]
Maybe try loading NeoJSON before ZincHTTPComponents.

Or use github://svenvc/NeoJSON:master/repository as URL

The master tag might cause some kind of version conflict in Metacello

Is NeoJSON already loaded/present before you execute the expression ?

What if you load NeoJSON using the expression in a fresh image ?

**Comment by riverdusty** [comment]
I've downloaded a fresh new image and a fresh new vm.
I've zipped them without opening, you can download it [here](https://wiki.evilcorp.ga/pharo.zip)
I've then opened the vm and tried to load NeoJSON as the first thing I did.
Comes up with Authentication Error.
Please try with the provided image to confirm.

**Comment by svenvc** [comment]
I quickly tried in a 7.0.5 image on my machine (macosx), which worked as expected, I will try later in other variations.

![Screenshot 2020-10-09 at 14 53 36](https://user-images.githubusercontent.com/870089/95585425-807fab00-0a3f-11eb-9af6-602786b5e7fa.png)

**Comment by riverdusty** [comment]
I suspect it has to be a pharo image/vm that is stand alone, and has no access to the host machines git/ssh environment. (Think if you sent an image to an end user and ask them to run that install script).

**Comment by riverdusty** [comment]
Confirmed, does NOT occure on Linux Mint with Pharo32bit. So seems to be a Windows thing.

**Comment by svenvc** [comment]
I don't understand what is going on.

You can load some of my other packages using github/tonel, but not that specific one. How is that even possible ?

I think it is best if you ask this question on the general mailing lists or discord channels, maybe refer to this issue.

**Comment by svenvc** [comment]
This seems outdated
