### ISSUE TITLE
Make NeoJSONObject subclass of OrderedDictionary

### ISSUE THREAD

**Issue by eMaringolo** [svenvc/NeoJSON#9]
It is somewhat annoying to have all the keys in a `NeoJSONObject` unsorted, given it is a subclass of Dictionary.

Wouldn't it be better to make `NeoJSONObject` a subclass of `OrderedDictionary`. This would make them easier to inspect and manipulate, and in the case that they were created by a `NeoJSONReader` using as a map class, then it would honor the order in which the keys were defined in the original JSON string.

**Comment by svenvc** [comment]
Maybe, and I'll think about it, but the fact is that the JSON spec clearly does not respect or define the order of properties within maps.

    An object is an unordered set of name/value pairs.

**Comment by eMaringolo** [comment]
I know the spec doesn't say so and I can also use an `OrderedDictionary` as the map class (without the DNU/path accessors of `NeoJSONObject`). But having the keys in an unpredictable order makes it harder to use.

E.g. in the browser (Chromium/FF) if you start with a JS `object` evaluating `Object.keys(object)` and `Object.keys(JSON.parse(JSON.stringify(object)))` both have the same keys in the same order, so both `parse`/`stringify` honor the order in which the keys were defined.

Let's put it the other way, what would be the drawbacks of making it a subclass of OrderedDictionary?

**Comment by svenvc** [comment]
https://github.com/svenvc/NeoJSON/commit/109d08bb08216b1ae583861a5c631cc0a564d248
